apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJlRk53WVhKTFNYZzZaMmh3WHpGWldISlFVMjlHY0dWS1YwSm9PRzlsVm1kcU4zZDBURkl3Y21ob05ETllVbWhEVGc9PSIKCQl9LAoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImVITndZWEpyYVhnNlVXRjZkM040TnpnMU5qRWgiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
